spring:
  datasource:
    url: jdbc:mysql://47.94.157.36:3306/live_team?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lin1997426520.
  redis:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    database: 0
    sentinel:
      master: mymaster
      nodes: 47.98.136.252:26379,47.98.136.252:26380,47.98.136.252:26381
    password: java1904
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  supportMethodsArguments: true
  reasonable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.live.liveteam.entity
logging:
  level:
    com.live.liveteam.mapper: DEBUG
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 47.94.157.36:22122
url:
  fastdfsurl: http://47.94.157.36:8888
server:
  port: 8080
